version: '3.8'

services:
  olu:
    build: .
    ports:
      - "9090:9090"
    environment:
      - HOST=0.0.0.0
      - PORT=9090
      - CACHE_TYPE=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RSERV_GRAPH=indexed
      - FULLTEXT_ENABLED=false
      - CASCADING_DELETE=false
    volumes:
      - ./data:/app/data
      - ./schema:/app/schema
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  redis_data:
